services:
  pgdatabase:
    image: postgres:13
    environment:
      - name=value
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - /c//Users//Neptune//Documents\\Projects\\postgres_fulltext_search\:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=tom@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80